# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '31 18 * * *'
    - cron: '31 22 * * *'
    - cron: '12 0 * * *'
    - cron: '48 2 * * *'
    - cron: '6 4 * * *'  
    - cron: '6 5 * * *'
    - cron: '36 6 * * *'
    - cron: '54 7 * * *'

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/playwright-github-action@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yagmail
        pip install playwright==1.8.0a1
    - name: Ensure browsers are installed
      run: python -m playwright install
    - name: Run your tests
      run: python main.py ${{ secrets.NUM }} ${{ secrets.PWD }} ${{ secrets.SEND_PWD }} ${{ secrets.TG }}
